"""Compatibility facade exposing the container API."""
from __future__ import annotations

from zilant_encrypt.container.core import (
    ARGON_MEM_MAX_KIB,
    ARGON_MEM_MIN_KIB,
    ARGON_PARALLELISM_MAX,
    ARGON_PARALLELISM_MIN,
    ARGON_TIME_MAX,
    ARGON_TIME_MIN,
    ModeLiteral,
    PayloadMeta,
    VolumeLayout,
    _decrypt_volume,
    _derive_file_key,
    _ensure_output,
    build_volume_descriptor,
    check_container,
    decrypt_auto_volume,
    decrypt_file,
    encrypt_file,
    encrypt_with_decoy,
    normalize_mode,
    resolve_argon_params,
)
from zilant_encrypt.container.format import RESERVED_LEN
from zilant_encrypt.container.keymgmt import (
    WRAP_NONCE,
    PasswordKeyProvider,
    WrappedKey,
    _validate_argon_params,
    _validate_decrypt_argon_params,
    _zeroize,
)
from zilant_encrypt.container.overview import (
    ContainerOverview,
    _ciphertext_length_for_descriptor,
    _load_overview,
    _select_descriptors,
)
from zilant_encrypt.container.payload import (
    MAX_PAYLOAD_META_LEN,
    PAYLOAD_MAGIC,
    PAYLOAD_META_LEN_SIZE,
    PAYLOAD_VERSION,
    STREAM_CHUNK_SIZE,
    _build_payload_header,
    _decrypt_stream,
    _encrypt_stream,
    _NullWriter,
    _PayloadSource,
    _PayloadWriter,
)
from zilant_encrypt.crypto.aead import TAG_LEN, AesGcmEncryptor

__all__ = [
    "ARGON_MEM_MAX_KIB",
    "ARGON_MEM_MIN_KIB",
    "ARGON_PARALLELISM_MAX",
    "ARGON_PARALLELISM_MIN",
    "ARGON_TIME_MAX",
    "ARGON_TIME_MIN",
    "MAX_PAYLOAD_META_LEN",
    "PAYLOAD_MAGIC",
    "PAYLOAD_META_LEN_SIZE",
    "PAYLOAD_VERSION",
    "AesGcmEncryptor",
    "TAG_LEN",
    "RESERVED_LEN",
    "PasswordKeyProvider",
    "PayloadMeta",
    "STREAM_CHUNK_SIZE",
    "VolumeLayout",
    "WrappedKey",
    "WRAP_NONCE",
    "_NullWriter",
    "_PayloadSource",
    "_PayloadWriter",
    "_build_payload_header",
    "_ciphertext_length_for_descriptor",
    "_decrypt_stream",
    "_decrypt_volume",
    "_derive_file_key",
    "_encrypt_stream",
    "_ensure_output",
    "_load_overview",
    "_select_descriptors",
    "_validate_argon_params",
    "_validate_decrypt_argon_params",
    "_zeroize",
    "build_volume_descriptor",
    "check_container",
    "decrypt_auto_volume",
    "decrypt_file",
    "encrypt_file",
    "encrypt_with_decoy",
    "normalize_mode",
    "resolve_argon_params",
    "ModeLiteral",
    "ContainerOverview",
]
